INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"
        font_family: Noto Sans SC

site_description: '一些世界各地的摇摆舞组织相关信息收录。'
nav:
  - 首页:
    - 地区: index.md
    - 标签: tags.md
    - 美洲:
      - 美国:
        - 总览: us/index.md
        - 城市: us/cities.md
        - 组织:
          - us/hot-rhythm-foundation.md
          - us/houston-swing-dance-society.md
          - us/ilindy.md
    - 亚洲:
      - 中国:
        - 总览: cn/index.md
        - 城市: cn/cities.md
        - 组织:
          - cn/a-frame.md
          - cn/a-jass-dance.md
          - cn/amoy-swing.md
          - cn/balboa-shenzhen.md
          - cn/blues-beijing.md
          - cn/blues-guang-zhou.md
          - cn/camel-walk-swing.md
          - cn/cats-corner-studio.md
          - cn/doo-the-swing.md
          - cn/double-swing.md
          - cn/downtown-swing.md
          - cn/flying-home.md
          - cn/go-swing-tientsin.md
          - cn/groove-blues-swing.md
          - cn/happy-swing.md
          - cn/he-cheng-swing.md
          - cn/he-fei-swing.md
          - cn/hi-swing.md
          - cn/hidden-swing.md
          - cn/ice-city-swing.md
          - cn/jin-swing.md
          - cn/laisi-swing-studio.md
          - cn/lizi-swing-dance-studio.md
          - cn/m-r-swing.md
          - cn/mala-swing.md
          - cn/nan-men-swing.md
          - cn/nb-swing.md
          - cn/rhythm-park.md
          - cn/seriously-swing-studio.md
          - cn/shi-men-swing.md
          - cn/smalls-swing.md
          - cn/so-dancing.md
          - cn/soul-city.md
          - cn/soul-swing.md
          - cn/swing-adventure.md
          - cn/swing-beasts.md
          - cn/swing-beijing.md
          - cn/swing-bing-zhou.md
          - cn/swing-canton.md
          - cn/swing-chang-sha.md
          - cn/swing-chong-qing.md
          - cn/swing-fo-shan.md
          - cn/swing-friends.md
          - cn/swing-fu-zhou.md
          - cn/swing-hang-zhou.md
          - cn/swing-hohhot.md
          - cn/swing-kun-ming.md
          - cn/swing-lan-zhou.md
          - cn/swing-land.md
          - cn/swing-nan-chang.md
          - cn/swing-nan-jing.md
          - cn/swing-shen-yang.md
          - cn/swing-shen-zhen.md
          - cn/swing-stars-studio.md
          - cn/swing-teoswa.md
          - cn/swing-tian-jin.md
          - cn/swing-time.md
          - cn/swing-topia.md
          - cn/swing-travels.md
          - cn/swing-wu-han.md
          - cn/swing-xi-an.md
          - cn/swing-zheng-zhou.md
          - cn/tabby-the-cat.md
          - cn/the-break-swing-dance.md
          - cn/tsing-tao-swing.md
          - cn/walking-the-blues.md
          - cn/yue-c-swing.md
          - cn/yun-swing.md
          - cn/zou-jin-yao-bai-wu.md
      - 香港:
        - 总览: hk/index.md
        - 城市: hk/cities.md
        - 组织:
          - hk/hong-kong-balboa.md
          - hk/hong-kong-swing.md
          - hk/rhythm-studio.md
          - hk/swing-pocket.md
      - 日本:
        - 总览: jp/index.md
        - 城市: jp/cities.md
        - 组织:
          - jp/chillboa.md
          - jp/dancing-bus.md
          - jp/kawasaki-swing.md
          - jp/osaka-swing.md
          - jp/sapporo-swing-dance.md
          - jp/sendai-swing-club.md
          - jp/swing-dance-kobe.md
          - jp/swing-gigolo.md
          - jp/swingin-barrelhouse-records.md
          - jp/swingin-niigata.md
          - jp/tokyo-swing-dance-society.md
      - 韩国:
        - 总览: kr/index.md
        - 城市: kr/cities.md
        - 组织:
          - kr/1st-bar.md
          - kr/asurajang.md
          - kr/babaru.md
          - kr/be-bop-bar.md
          - kr/big-apple-cheonan.md
          - kr/big-apple-seoul.md
          - kr/bongchun-salon.md
          - kr/clave.md
          - kr/cloud-9-dance-hall.md
          - kr/club-ann.md
          - kr/fiesta-2.md
          - kr/happy-hall.md
          - kr/hoppers-hall.md
          - kr/in-the-mood-sillim.md
          - kr/kyungsung-hall.md
          - kr/lala-hall.md
          - kr/mayan.md
          - kr/rico.md
          - kr/salon-de-cheonan.md
          - kr/savoy-ballroom.md
          - kr/swing-243-dance-hall.md
          - kr/swing-bar.md
          - kr/swing-it-dance-hall.md
          - kr/swing-latte.md
          - kr/swing-time-bar.md
          - kr/the-k-dance-studio.md
          - kr/the-social-club.md
          - kr/triple-crown.md
          - kr/wing-bar.md
      - 泰国:
        - 总览: th/index.md
        - 城市: th/cities.md
        - 组织:
          - th/the-hop-bangkok.md
      - 台湾:
        - 总览: tw/index.md
        - 城市: tw/cities.md
        - 组织:
          - tw/big-apple-swing-studio.md
          - tw/friday-swing.md
          - tw/jf-swing.md
          - tw/lets-swing-taichung.md
          - tw/naughty-swing.md
          - tw/swing-fomosa.md
          - tw/swing-gale.md
          - tw/swing-tai-wan.md
          - tw/switch-taipei.md
          - tw/tap-life.md
    - 欧洲:
      - 德国:
        - 总览: de/index.md
        - 城市: de/cities.md
        - 组织:
          - de/let-it-swing.md
      - 法国:
        - 总览: fr/index.md
        - 城市: fr/cities.md
        - 组织:
          - fr/swingtime-bordeaux.md
  - 活动: https://swing.news/zh-Hans
  - 更新日志: https://github.com/swingdance/orgs/commits/main/
  - 关于:
    - references.md
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: submit.md
