INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

site_description: 'A collection of swing dance orgs from around the world.'
nav:
  - 首页:
    - 地区: index.md
    - 标签: tags.md
    - 美洲:
      - en_US • 美国:
        - 总览: en_US/index.md
        - 城市: en_US/cities.md
        - 组织:
          - en_US/hot-rhythm-foundation.md
          - en_US/ilindy.md
    - 亚洲:
      - ja_JP • 日本:
        - 总览: ja_JP/index.md
        - 城市: ja_JP/cities.md
        - 组织:
          - ja_JP/chillboa.md
          - ja_JP/dancing-bus.md
          - ja_JP/kawasaki-swing.md
          - ja_JP/osaka-swing.md
          - ja_JP/sapporo-swing-dance.md
          - ja_JP/sendai-swing-club.md
          - ja_JP/swing-dance-kobe.md
          - ja_JP/swing-gigolo.md
          - ja_JP/swingin-barrelhouse-records.md
          - ja_JP/swingin-niigata.md
          - ja_JP/tokyo-swing-dance-society.md
      - ko_KR • 韩国:
        - 总览: ko_KR/index.md
        - 城市: ko_KR/cities.md
        - 组织:
          - ko_KR/1st-bar.md
          - ko_KR/asurajang.md
          - ko_KR/babaru.md
          - ko_KR/be-bop-bar.md
          - ko_KR/big-apple-cheonan.md
          - ko_KR/big-apple-seoul.md
          - ko_KR/bongchun-salon.md
          - ko_KR/clave.md
          - ko_KR/cloud-9-dance-hall.md
          - ko_KR/club-ann.md
          - ko_KR/fiesta-2.md
          - ko_KR/happy-hall.md
          - ko_KR/hoppers-hall.md
          - ko_KR/in-the-mood-sillim.md
          - ko_KR/kyungsung-hall.md
          - ko_KR/lala-hall.md
          - ko_KR/mayan.md
          - ko_KR/rico.md
          - ko_KR/salon-de-cheonan.md
          - ko_KR/savoy-ballroom.md
          - ko_KR/swing-243-dance-hall.md
          - ko_KR/swing-bar.md
          - ko_KR/swing-it-dance-hall.md
          - ko_KR/swing-latte.md
          - ko_KR/swing-time-bar.md
          - ko_KR/the-k-dance-studio.md
          - ko_KR/the-social-club.md
          - ko_KR/triple-crown.md
          - ko_KR/wing-bar.md
      - th_TH • 泰国:
        - 总览: th_TH/index.md
        - 城市: th_TH/cities.md
        - 组织:
          - th_TH/the-hop-bangkok.md
      - zh_CN • 中国:
        - 总览: zh_CN/index.md
        - 城市: zh_CN/cities.md
        - 组织:
          - zh_CN/a-frame.md
          - zh_CN/a-jass-dance.md
          - zh_CN/amoy-swing.md
          - zh_CN/blues-beijing.md
          - zh_CN/blues-guang-zhou.md
          - zh_CN/camel-walk-swing.md
          - zh_CN/cats-corner-studio.md
          - zh_CN/doo-the-swing.md
          - zh_CN/double-swing.md
          - zh_CN/downtown-swing.md
          - zh_CN/flying-home.md
          - zh_CN/go-swing-tientsin.md
          - zh_CN/groove-blues-swing.md
          - zh_CN/happy-swing.md
          - zh_CN/he-cheng-swing.md
          - zh_CN/he-fei-swing.md
          - zh_CN/hi-swing.md
          - zh_CN/hidden-swing.md
          - zh_CN/ice-city-swing.md
          - zh_CN/jin-swing.md
          - zh_CN/laisi-swing-studio.md
          - zh_CN/lizi-swing-dance-studio.md
          - zh_CN/m-r-swing.md
          - zh_CN/mala-swing.md
          - zh_CN/nan-men-swing.md
          - zh_CN/nb-swing.md
          - zh_CN/rhythm-park.md
          - zh_CN/seriously-swing-studio.md
          - zh_CN/shi-men-swing.md
          - zh_CN/smalls-swing.md
          - zh_CN/so-dancing.md
          - zh_CN/soul-swing.md
          - zh_CN/swing-adventure.md
          - zh_CN/swing-beasts.md
          - zh_CN/swing-beijing.md
          - zh_CN/swing-bing-zhou.md
          - zh_CN/swing-canton.md
          - zh_CN/swing-chang-sha.md
          - zh_CN/swing-chong-qing.md
          - zh_CN/swing-fo-shan.md
          - zh_CN/swing-friends.md
          - zh_CN/swing-fu-zhou.md
          - zh_CN/swing-hang-zhou.md
          - zh_CN/swing-hohhot.md
          - zh_CN/swing-kun-ming.md
          - zh_CN/swing-lan-zhou.md
          - zh_CN/swing-land.md
          - zh_CN/swing-nan-chang.md
          - zh_CN/swing-nan-jing.md
          - zh_CN/swing-shen-yang.md
          - zh_CN/swing-shen-zhen.md
          - zh_CN/swing-stars-studio.md
          - zh_CN/swing-teoswa.md
          - zh_CN/swing-tian-jin.md
          - zh_CN/swing-time.md
          - zh_CN/swing-topia.md
          - zh_CN/swing-travels.md
          - zh_CN/swing-wu-han.md
          - zh_CN/swing-xi-an.md
          - zh_CN/swing-zheng-zhou.md
          - zh_CN/tabby-the-cat.md
          - zh_CN/the-break-swing-dance.md
          - zh_CN/tsing-tao-swing.md
          - zh_CN/yue-c-swing.md
          - zh_CN/yun-swing.md
          - zh_CN/zou-jin-yao-bai-wu.md
      - zh_HK • 香港:
        - 总览: zh_HK/index.md
        - 城市: zh_HK/cities.md
        - 组织:
          - zh_HK/hong-kong-balboa.md
          - zh_HK/hong-kong-swing.md
          - zh_HK/rhythm-studio.md
          - zh_HK/swing-pocket.md
      - zh_TW • 台湾:
        - 总览: zh_TW/index.md
        - 城市: zh_TW/cities.md
        - 组织:
          - zh_TW/big-apple-swing-studio.md
          - zh_TW/friday-swing.md
          - zh_TW/jf-swing.md
          - zh_TW/lets-swing-taichung.md
          - zh_TW/naughty-swing.md
          - zh_TW/swing-fomosa.md
          - zh_TW/swing-gale.md
          - zh_TW/swing-tai-wan.md
          - zh_TW/switch-taipei.md
          - zh_TW/tap-life.md
  - 活动: https://swing.news
  - 更新日志: https://github.com/swingdance/orgs/commits/main/
  - 关于:
    - references.md
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: submit.md
