INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"

site_description: 'A collection of swing dance orgs from around the world.'
nav:
  - Home:
    - Regions: index.md
    - Tags: tags.md
    - America:
      - United States:
        - Overview: us/index.md
        - Cities: us/cities.md
        - Orgs:
          - us/hot-rhythm-foundation.md
          - us/houston-swing-dance-society.md
          - us/ilindy.md
    - Asia:
      - China:
        - Overview: cn/index.md
        - Cities: cn/cities.md
        - Orgs:
          - cn/a-frame.md
          - cn/a-jass-dance.md
          - cn/amoy-swing.md
          - cn/balboa-shenzhen.md
          - cn/blues-beijing.md
          - cn/blues-guang-zhou.md
          - cn/camel-walk-swing.md
          - cn/cats-corner-studio.md
          - cn/doo-the-swing.md
          - cn/double-swing.md
          - cn/downtown-swing.md
          - cn/flying-home.md
          - cn/go-swing-tientsin.md
          - cn/groove-blues-swing.md
          - cn/happy-swing.md
          - cn/he-cheng-swing.md
          - cn/he-fei-swing.md
          - cn/hi-swing.md
          - cn/hidden-swing.md
          - cn/ice-city-swing.md
          - cn/jin-swing.md
          - cn/laisi-swing-studio.md
          - cn/lizi-swing-dance-studio.md
          - cn/m-r-swing.md
          - cn/mala-swing.md
          - cn/nan-men-swing.md
          - cn/nb-swing.md
          - cn/rhythm-park.md
          - cn/seriously-swing-studio.md
          - cn/shi-men-swing.md
          - cn/smalls-swing.md
          - cn/so-dancing.md
          - cn/soul-city.md
          - cn/soul-swing.md
          - cn/swing-adventure.md
          - cn/swing-beasts.md
          - cn/swing-beijing.md
          - cn/swing-bing-zhou.md
          - cn/swing-canton.md
          - cn/swing-chang-sha.md
          - cn/swing-chong-qing.md
          - cn/swing-fo-shan.md
          - cn/swing-friends.md
          - cn/swing-fu-zhou.md
          - cn/swing-hang-zhou.md
          - cn/swing-hohhot.md
          - cn/swing-kun-ming.md
          - cn/swing-lan-zhou.md
          - cn/swing-land.md
          - cn/swing-nan-chang.md
          - cn/swing-nan-jing.md
          - cn/swing-shen-yang.md
          - cn/swing-shen-zhen.md
          - cn/swing-stars-studio.md
          - cn/swing-teoswa.md
          - cn/swing-tian-jin.md
          - cn/swing-time.md
          - cn/swing-topia.md
          - cn/swing-travels.md
          - cn/swing-wu-han.md
          - cn/swing-xi-an.md
          - cn/swing-zheng-zhou.md
          - cn/tabby-the-cat.md
          - cn/the-break-swing-dance.md
          - cn/tsing-tao-swing.md
          - cn/walking-the-blues.md
          - cn/yue-c-swing.md
          - cn/yun-swing.md
          - cn/zou-jin-yao-bai-wu.md
      - Hong Kong:
        - Overview: hk/index.md
        - Cities: hk/cities.md
        - Orgs:
          - hk/hong-kong-balboa.md
          - hk/hong-kong-swing.md
          - hk/rhythm-studio.md
          - hk/swing-pocket.md
      - Japan:
        - Overview: jp/index.md
        - Cities: jp/cities.md
        - Orgs:
          - jp/chillboa.md
          - jp/dancing-bus.md
          - jp/kawasaki-swing.md
          - jp/osaka-swing.md
          - jp/sapporo-swing-dance.md
          - jp/sendai-swing-club.md
          - jp/swing-dance-kobe.md
          - jp/swing-gigolo.md
          - jp/swingin-barrelhouse-records.md
          - jp/swingin-niigata.md
          - jp/tokyo-swing-dance-society.md
      - South Korea:
        - Overview: kr/index.md
        - Cities: kr/cities.md
        - Orgs:
          - kr/1st-bar.md
          - kr/asurajang.md
          - kr/babaru.md
          - kr/be-bop-bar.md
          - kr/big-apple-cheonan.md
          - kr/big-apple-seoul.md
          - kr/bongchun-salon.md
          - kr/clave.md
          - kr/cloud-9-dance-hall.md
          - kr/club-ann.md
          - kr/fiesta-2.md
          - kr/happy-hall.md
          - kr/hoppers-hall.md
          - kr/in-the-mood-sillim.md
          - kr/kyungsung-hall.md
          - kr/lala-hall.md
          - kr/mayan.md
          - kr/rico.md
          - kr/salon-de-cheonan.md
          - kr/savoy-ballroom.md
          - kr/swing-243-dance-hall.md
          - kr/swing-bar.md
          - kr/swing-it-dance-hall.md
          - kr/swing-latte.md
          - kr/swing-time-bar.md
          - kr/the-k-dance-studio.md
          - kr/the-social-club.md
          - kr/triple-crown.md
          - kr/wing-bar.md
      - Thailand:
        - Overview: th/index.md
        - Cities: th/cities.md
        - Orgs:
          - th/the-hop-bangkok.md
      - Taiwan:
        - Overview: tw/index.md
        - Cities: tw/cities.md
        - Orgs:
          - tw/big-apple-swing-studio.md
          - tw/friday-swing.md
          - tw/jf-swing.md
          - tw/lets-swing-taichung.md
          - tw/naughty-swing.md
          - tw/swing-fomosa.md
          - tw/swing-gale.md
          - tw/swing-tai-wan.md
          - tw/switch-taipei.md
          - tw/tap-life.md
    - Europe:
      - Germany:
        - Overview: de/index.md
        - Cities: de/cities.md
        - Orgs:
          - de/let-it-swing.md
  - Events: https://swing.news
  - Changelogs: https://github.com/swingdance/orgs/commits/main/
  - About:
    - references.md
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: submit.md
